// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2YvVpfQ3RXUHdM63y637YrHvJWZ8vsDo',
    appId: '1:661850068763:web:59a340a860d821760be5be',
    messagingSenderId: '661850068763',
    projectId: 'expense-tracker-1e3a2',
    authDomain: 'expense-tracker-1e3a2.firebaseapp.com',
    storageBucket: 'expense-tracker-1e3a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoKpR3vOFyWqsu1D5wDBMeVErKAU6rI1U',
    appId: '1:661850068763:android:ed0eb1346045400b0be5be',
    messagingSenderId: '661850068763',
    projectId: 'expense-tracker-1e3a2',
    storageBucket: 'expense-tracker-1e3a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZy2EV1yG2dVDPBWrxmF3dhjOSIfIUhxI',
    appId: '1:661850068763:ios:16058248151dfb650be5be',
    messagingSenderId: '661850068763',
    projectId: 'expense-tracker-1e3a2',
    storageBucket: 'expense-tracker-1e3a2.firebasestorage.app',
    iosClientId: '661850068763-g0p1vec300rfba3d1qhe5519jtqf3ius.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZy2EV1yG2dVDPBWrxmF3dhjOSIfIUhxI',
    appId: '1:661850068763:ios:16058248151dfb650be5be',
    messagingSenderId: '661850068763',
    projectId: 'expense-tracker-1e3a2',
    storageBucket: 'expense-tracker-1e3a2.firebasestorage.app',
    iosClientId: '661850068763-g0p1vec300rfba3d1qhe5519jtqf3ius.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2YvVpfQ3RXUHdM63y637YrHvJWZ8vsDo',
    appId: '1:661850068763:web:8cffdebf9d9e3f5b0be5be',
    messagingSenderId: '661850068763',
    projectId: 'expense-tracker-1e3a2',
    authDomain: 'expense-tracker-1e3a2.firebaseapp.com',
    storageBucket: 'expense-tracker-1e3a2.firebasestorage.app',
  );
}
